const $=id=>document.getElementById(id);const KEY='bizimRotalarimizV1';
let data=JSON.parse(localStorage.getItem(KEY)||'{"trips":[],"wish":[]}');let map,liveLine,markers=[],watchId=null,current=null,poiLayer=[];
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderStats();renderTrips()}
function fmt(ms){let m=Math.max(0,Math.round(ms/60000));let h=Math.floor(m/60);m%=60;return h?`${h} saat ${m} dk`:`${m} dk`}
function km(m){return (m/1000).toFixed(1)}
function dist(a,b){const R=6371e3,p=Math.PI/180,x=(b.lat-a.lat)*p,y=(b.lng-a.lng)*p,z=Math.sin(x/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function initMap(){map=L.map('mapView').setView([39,35],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);renderHistory()}
function renderHistory(){markers.forEach(x=>map.removeLayer(x));markers=[];data.trips.forEach(t=>{if(t.points?.length>1){let l=L.polyline(t.points.map(p=>[p.lat,p.lng]),{weight:4,opacity:.45}).addTo(map);l.bindPopup(`<b>${t.name}</b><br>${new Date(t.start).toLocaleDateString('tr-TR')}<br>${km(t.distance)} km · ${fmt(t.end-t.start)}`);markers.push(l)}t.stops?.forEach(s=>{let m=L.marker([s.lat,s.lng]).addTo(map).bindPopup(`<b>${s.name}</b><br>${fmt(s.duration||0)}<br>${new Date(s.start).toLocaleString('tr-TR')}`);markers.push(m)})})}
async function geocode(q){let r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q),{headers:{'Accept-Language':'tr'}});let a=await r.json();if(!a[0])throw Error('Yer bulunamadı');return {lat:+a[0].lat,lng:+a[0].lon,name:a[0].display_name}}
async function poi(lat,lng){let q=`[out:json];(nwr(around:25000,${lat},${lng})[tourism];nwr(around:25000,${lat},${lng})[historic];);out center 30;`;let r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q});let a=await r.json();return a.elements.map(x=>({name:x.tags?.name||x.tags?.['name:tr']||'Turistik nokta',lat:x.lat||x.center?.lat,lng:x.lon||x.center?.lon,type:x.tags?.tourism||x.tags?.historic||'turistik'})).filter(x=>x.lat&&x.lng)}
$('planBtn').onclick=async()=>{try{$('planBtn').textContent='Aranıyor…';let d=await geocode($('destination').value);map.setView([d.lat,d.lng],10);poiLayer.forEach(x=>map.removeLayer(x));let ps=await poi(d.lat,d.lng);$('suggestions').innerHTML=`<div class="card"><h3>✨ ${d.name}</h3><p>Otomatik bulunan turistik duraklardan istediklerinizi gezi planına ekleyebilirsiniz.</p></div>`+ps.map((p,i)=>`<div class="card"><b>${i+1}. ${p.name}</b><div><span class="tag">${p.type}</span><button onclick="addWish(${p.lat},${p.lng},${JSON.stringify(p.name)})">⭐ Listeye ekle</button></div></div>`).join('');ps.forEach(p=>{let m=L.circleMarker([p.lat,p.lng],{radius:7}).addTo(map).bindPopup(`<b>${p.name}</b><br><button onclick="addWish(${p.lat},${p.lng},${JSON.stringify(p.name)})">⭐ Gitmek istiyoruz</button>`);poiLayer.push(m)});data.wish=ps;save()}catch(e){alert(e.message)}finally{$('planBtn').textContent='✨ Akıllı Plan'}};
window.addWish=(lat,lng,name)=>{data.wish.push({lat,lng,name});save();alert('Gitmek istediklerinize eklendi ⭐')}
$('startTrip').onclick=()=>{if(!navigator.geolocation)return alert('Bu cihaz konum takibini desteklemiyor.');current={name:$('tripName').value.trim()||'Yeni Gezi',start:Date.now(),end:null,points:[],stops:[],distance:0,driveMs:0,stopMs:0,lastMove:Date.now(),stopStart:null,media:[]};$('tripState').textContent='Takip ediliyor';watchId=navigator.geolocation.watchPosition(pos=>{let p={lat:pos.coords.latitude,lng:pos.coords.longitude,t:Date.now(),speed:pos.coords.speed};let a=current.points.at(-1);if(a){let d=dist(a,p);if(d>3){current.distance+=d;let dt=p.t-a.t;if((p.speed||0)>1){current.driveMs+=dt;if(current.stopStart){let s=current.stops.at(-1);if(s&&!s.end){s.end=p.t;s.duration=s.end-s.start;current.stopMs+=s.duration}current.stopStart=null}}else if(dt>300000&&!current.stopStart){current.stopStart=a.t;current.stops.push({name:'Otomatik durak',lat:a.lat,lng:a.lng,start:a.t,end:null,duration:0,media:[]})}}}current.points.push(p);updateLive()},e=>alert('Konum hatası: '+e.message),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function updateLive(){if(!current)return;let total=Date.now()-current.start;$('tripDuration').textContent=fmt(total);$('driveDuration').textContent=fmt(current.driveMs);$('stopDuration').textContent=fmt(current.stopMs+(current.stopStart?Date.now()-current.stopStart:0));$('tripDistance').textContent=km(current.distance)+' km';$('stopList').innerHTML=current.stops.map((s,i)=>`<div class="card"><b>📍 ${s.name}</b><p>${new Date(s.start).toLocaleTimeString('tr-TR')} · ${fmt(s.duration||Date.now()-s.start)}</p><div class="stopActions"><button onclick="renameStop(${i})">✏️ Adlandır</button><button onclick="mediaStop(${i})">📷 Foto/Video</button></div></div>`).join('');if(liveLine)map.removeLayer(liveLine);if(current.points.length>1){liveLine=L.polyline(current.points.map(p=>[p.lat,p.lng]),{weight:5}).addTo(map);map.panTo(current.points.at(-1))}}
window.renameStop=i=>{let n=prompt('Durak adı',current.stops[i].name);if(n){current.stops[i].name=n;updateLive()}};window.mediaStop=i=>pickMedia(files=>{current.stops[i].media.push(...files);updateLive()});
function pickMedia(cb){let x=document.createElement('input');x.type='file';x.accept='image/*,video/*';x.multiple=true;x.onchange=()=>Promise.all([...x.files].map(f=>new Promise(r=>{let rd=new FileReader();rd.onload=()=>r({name:f.name,type:f.type,data:rd.result});rd.readAsDataURL(f)}))).then(cb);x.click()}
$('stopTrip').onclick=()=>{if(!current)return;if(watchId!==null)navigator.geolocation.clearWatch(watchId);current.end=Date.now();if(current.stopStart){let s=current.stops.at(-1);s.end=current.end;s.duration=s.end-s.start;current.stopMs+=s.duration}data.trips.unshift(current);current=null;watchId=null;$('tripState').textContent='Kaydedildi';save();renderHistory();if(liveLine){map.removeLayer(liveLine);liveLine=null}alert('Gezi kaydedildi ❤️')}
function renderTrips(){$('tripCards').innerHTML=data.trips.map((t,i)=>`<div class="card"><h3>🚗 ${t.name}</h3><p>${new Date(t.start).toLocaleDateString('tr-TR')} · ${km(t.distance)} km</p><span class="tag">🚗 ${fmt(t.driveMs||0)}</span><span class="tag">📍 ${fmt(t.stopMs||0)}</span><span class="tag">${t.stops?.length||0} durak</span><div class="stopActions"><button onclick="showTrip(${i})">🗺️ Harita & Albüm</button><button class="danger" onclick="deleteTrip(${i})">Sil</button></div></div>`).join('')||'<div class="card">Henüz kayıtlı gezi yok. İlk yolculuğunuzu başlatın! ❤️</div>'}
window.deleteTrip=i=>{if(confirm('Bu gezi silinsin mi?')){data.trips.splice(i,1);save();renderHistory()}};window.showTrip=i=>{let t=data.trips[i];$('modalBody').innerHTML=`<h2>${t.name}</h2><p>${new Date(t.start).toLocaleString('tr-TR')} → ${new Date(t.end).toLocaleString('tr-TR')}</p><p>🛣️ ${km(t.distance)} km · 🚗 ${fmt(t.driveMs||0)} · 📍 ${fmt(t.stopMs||0)}</p>`+(t.stops||[]).map(s=>`<div class="card"><b>📍 ${s.name}</b><p>${fmt(s.duration||0)}</p><div class="mediaGrid">${(s.media||[]).map(m=>m.type.startsWith('video')?`<video controls src="${m.data}"></video>`:`<img src="${m.data}">`).join('')}</div></div>`).join('');$('modal').classList.remove('hidden');$('mapView').style.display='none';document.querySelector('[data-tab="map"]').click();setTimeout(()=>{map.invalidateSize();if(t.points?.length){let l=L.polyline(t.points.map(p=>[p.lat,p.lng]),{weight:6}).addTo(map);map.fitBounds(l.getBounds());setTimeout(()=>map.removeLayer(l),20000)}},100)};
$('closeModal').onclick=()=>{$('modal').classList.add('hidden')};
function renderStats(){let ts=data.trips,cities=new Set();let kmAll=0,drive=0,stops=0;ts.forEach(t=>{kmAll+=t.distance||0;drive+=t.driveMs||0;stops+=t.stopMs||0;(t.stops||[]).forEach(s=>{if(s.name&&s.name!=='Otomatik durak')cities.add(s.name.split(' ')[0])})});let n=Math.min(cities.size,81),pct=(n/81*100).toFixed(1);$('cityCount').textContent=`${n} / 81`;$('explorePercent').textContent=`%${pct}`;$('allTrips').textContent=ts.length;$('allKm').textContent=km(kmAll)+' km';$('allDrive').textContent=fmt(drive);$('allStops').textContent=fmt(stops);$('progressBar').style.width=pct+'%';let longest=[...ts].sort((a,b)=>(b.distance||0)-(a.distance||0))[0];$('summary').innerHTML=longest?`<div class="card"><b>🏆 En uzun yolculuk</b><p>${longest.name} · ${km(longest.distance)} km</p></div>`:'<div class="card">İlk gezinizden sonra burada keşif özetleriniz görünecek.</div>'}
$('exportBtn').onclick=()=>{let b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='BizimRotalarimiz_Yedek_'+new Date().toISOString().slice(0,10)+'.json';a.click()};$('importFile').onchange=e=>{let r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();renderHistory();alert('Yedek yüklendi')}catch{alert('Geçersiz yedek')}};r.readAsText(e.target.files[0])};$('clearBtn').onclick=()=>{if(confirm('Tüm veriler silinecek. Emin misiniz?')){data={trips:[],wish:[]};save();renderHistory()}}
$('tabs').onclick=e=>{let b=e.target.closest('button[data-tab]');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active');b.classList.add('active');if(b.dataset.tab==='map'){setTimeout(()=>map.invalidateSize(),100)}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');window.onload=()=>{initMap();renderTrips();renderStats()};
